import Home from "./Home";
import Login from "./Login";
import Profile from "./Profile";
import Register from "./Register";
import ResetPassword from "./ResetPassword";
import EnternewPassword from "./EnternewPassword";
import EmailVerification from "./EmailVerification";
import GoogleRedirect from "./GoogleRedirect";
import NotFound from "./NotFound";
export { Home, Login, Profile, Register, ResetPassword, EnternewPassword, EmailVerification, GoogleRedirect, NotFound };